### ISSUE TITLE
안드로이드 앱 실행 후 중단됩니다

### ISSUE THREAD

**Issue by BreathingCapybara** [droidknights/DroidKnights-Festival-2019-flutter#64]
스플래시 후 메인으로 넘어온 상태에서 가만히 있으면 화면이 중단됩니다. 계속 실행하면 계속 중당된다는 안드로이드 메세지가 나타납니다

**Comment by Jiyoung9310** [comment]
안드로이드 OS 9.0 버전에서만 나타나는 것으로 확인되고 있습니다.
혹시 다른 버전에서도 나타나면 커맨드 달아주세요!

**Comment by neulbo27** [comment]
9.0 사용하고 있어서 logcat으로 확인해본 결과 apache http 라이브러리 사용으로 인해 앱이 종료되는 것으로 보입니다.
https://developer.android.com/about/versions/pie/android-9.0-changes-28?hl=ko#apache-p

>2019-03-29 12:23:57.432 3582-3685/? E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.droidknights.flutterdroidknights, PID: 3582
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
        at fb.b(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):3)
        at fa.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):3)
        at fc.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):15)
        at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):6)
        at ee.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):23)
        at ee.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):8)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000086/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000086/MapsDynamite.apk!/lib/armeabi-v7a, /data/user_de/0/com.google.android.gms/app_chimera/m/00000086/MapsDynamite.apk!/lib/armeabi, /system/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at ac.loadClass(:com.google.android.gms.dynamite_dynamiteloader@16089081@16.0.89 (100400-239467275):4)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at fb.b(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):3) 
        at fa.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):3) 
        at fc.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):15) 
        at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):6) 
        at ee.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):23) 
        at ee.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):8)

**Comment by Jiyoung9310** [comment]
제보 감사합니다! 그래들과 매니패스트 파일에 http apache 관련해서 코드 추가했습니다

**Comment by Jiyoung9310** [comment]
앱 버전 1.2.1 에서 동작 됩니다! 업데이트 바랍니다
